grc/digitizers_picoscope_6000.xml, lib/digitizer_block_impl.cc, lib/picoscope_6000_impl.cc
So far the AUX input of the ps6000 was threat like a digital input.
Surprisingly that often worked well. but has issues (Looks like it used a threashold of 0V)
E.g. when mutible ps6000 are triggered via the same trigger source, some 'magic' is going on which lets the second scope trigger delayed.
This patch fixes the problem my threading the AUX trigger as an analog trigger. According to the programmer-manual it has a Range of +/-1V. (Raw-value calculation for the trigger threashold anyhow was broken, since it did not consider the channel range)
=> Thread AUX trigger as analog Trigger

lib/picoscope_6000_impl.cc
Just a small modification to more clearly show which serial is searched for and which serials were found.
- Increased readibilty of info messages
- 'sucess' message when ps6000 is found
- Usage of GR_LOG_INFO
- style fixes
=> Improved debugging / console messages for ps6000 scope detection

include/digitizers/status.h, lib/picoscope_impl.cc
Required in FESA (cannot match WR-events to trigger tags when trigger tags are possibly are missing)
Tested on dal007 (4x ps4000 system) ... already helped me to find a good buffer size
=> Add "BUFFERS_LOST" information into status of acq_info tag

lib/digitizer_block_impl.cc
I was just debugging something else, than it happened out of nothing: The Digitizer does not deliver any data any more directly after startup.
Using directly the pico4000 raw driver still worked. I remeber I saw that effect before and it was gone after a reboot. 
First I tried to revert my changes .. did not help. The effect seems to be heree to stay.
So this time I tracked it down instead of rebooting, and found out that the method `boost::this_thread::sleep_for(boost::chrono::microseconds(100));` does not return control for unknown reason. (Hey, thats supposed to be just a nanosleep :disappointed: )
Replacing the boost methods with` std::` equivalents fixed the issue.
=> Replace boost sleep methods by std sleep methods

lib/decimate_and_adjust_timebase_impl.cc, lib/freq_estimator_impl.cc
Issue #33
Sorry, looks like what I did before in that method was much too complex. It is sufficient to just divide the `offset` by `decim` for each tag added to the output stream. (Tested on 4 picoscope system while counting incoming trigger tags and comparing them with the expected number)
The block is a "sync decimator", and therefor knows about it's decimation factor. So it theoretically should as well work to just use` tag_propagation_policy_t::TPP_ONE_TO_ONE`. Though I filed a bug against gnuradio regarding that, because using that seems to slowly eat memory in some consitions: https://github.com/gnuradio/gnuradio/issues/2364
=> Decimate and adjust timebase: Simplify tag propagation

lib/digitizer_block_impl.h, lib/picoscope_3000a_impl.cc, lib/picoscope_4000a_impl.cc, lib/picoscope_6000_impl.cc
Instead of mixing float/double, which leads to comparison failure
This fixes the problem described in https://github.com/fair-acc/gr-digitizers/issues/97  (comparison works fine now)
( Though I still would prefer the usage of enum values, to be more failsafe. This is just a "quickfix" to get stuff running. )
Currently at least two productive ps3000 devices suffer from this bug (whether the bug shows seems to dependent on the choosen channel ranges)
=> Consistently use double for ranges (Issue #79)

lib/digitizer_block_impl.cc
Was only wrong for streaming mode, works fine for triggered mode(Rapid
Block)
Primary an issue to display the trigger-input-channel for ps3000 scopes
(triggered by digital ports) if channels are disabled.
Possibly related: https://github.com/fair-acc/gr-digitizers/issues/80
Tested with dal011 (HF Streaming System on which Channels C and D are disabled)
=> Tags added to wrong channel if channels are disabled

lib/digitizer_block_impl.cc
In order to Make Configuration errors at least more visible
I did not find out whats the consequence of returning "false" in `start`, seems to make no difference.
I suppose Fesa should check `d_configure_exception_message` and stop/abort the flowgraph when it is filled.
Fixes https://github.com/fair-acc/gr-digitizers/issues/95
=> Log Error when Exception occurs during start/configure (Issue #95)

lib/digitizer_block_impl.cc
I was to quick with adding that warning in #92. The warning was printed alot on different servers, filling up our graylog with nonsense messages.
I tried to increase the poll duration to get rid of the warning. Though for some frontends, as soon as no warning was displayed, the number of received samples per time on the FESA side did not match the expectations any more (in some cases as well lost buffers were observed).
So I suppose it is normal / can be expected that ocasionally no waiting needs to be done, and it should not lead to a warning.
=> Remove noisy warning

.github/workflows/ci.yml
v1 of the action uses java11 which will not be supported after end of this month.
=> CI: update sonar-scanner action to v2

CMakeLists.txt, blocklib/timing/src/test-timing.cpp
ImGUI had a regression in the dynamic loader for libGL. This commit improves diagnostic logging and bumps imgui to a version containing the fix.
See https://github.com/ocornut/imgui/commit/a3eea8a75a073694df72a31530632804df0001ec
=> test-timing: more debug output for sdl+gl3 init and bump imgui

CMakeLists.txt, blocklib/timing/CMakeLists.txt
When adding gr-digitizers to a build using add_subdirectory or fetch_content, the targets for the ui tools and dependencies can clash. This commit removes them from the build if this project is not the top-level cmake project.
Also default disables gr-digitizer tests in that case by default.
Longer term we should improve the cmake in all projects to allow overriding dependencies and correctly use cmake namespaces for the targets...
=> cmake: only add ui tools and their dependencies in toplevel build

CMakeLists.txt, blocklib/helpers/HelperBlocks.hpp, blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/Picoscope4000a.hpp, blocklib/picoscope/test/CMakeLists.txt, blocklib/picoscope/test/qa_Picoscope4000a.cc
Bump to latest graph-prototype and fix the regressions with Picoscope4000a by adapting to the new lifecycle API.
=> Fix qa_Picoscope4000a regressions

CMakeLists.txt, blocklib/picoscope/Picoscope.hpp, blocklib/timing/CMakeLists.txt, blocklib/timing/include/timing.hpp, blocklib/timing/test/CMakeLists.txt
minor fixes:
* `CircularBuffer::reserve_output_range(nSamples)` -> `CircularBuffer::reserve(nSamples)`
* changed/removed manual block state handling in Picoscope
* removed superfluous ';'
**EDIT:**
clang/libc++ does not support the required `<chrono>` features to convert from TAI to UTC and `std::views::enumerate`. I looked into basic workarounds but this became rather ugly. Since this should be solved by itself rather soon (both things are being actively worked upon within clang/libc++),  I thus disabled the timing-related blocks and unit-tests for the time being for Emscripten and Clang.
=> bump to latest GR4.0-alpha

CMakeLists.txt
Use latest graph-prototype and update to the ut used in there.
=> Bump graph-prototype and ut

CMakeLists.txt, blocklib/helpers/HelperBlocks.hpp, blocklib/picoscope/CMakeLists.txt, blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/Picoscope4000a.hpp, blocklib/picoscope/Picoscope5000a.hpp, blocklib/picoscope/test/CMakeLists.txt, blocklib/picoscope/test/qa_Picoscope.cc, blocklib/picoscope/test/qa_Picoscope4000a.cc
As discussed, this implements all of the following items:
- Restrict Picoscope value types to `int16_t`, `float` and `gr::UncertainValue<float>`
- Remove the custom `work()` implementation and port Picoscope to use `processBulk()`
- `BlockingIO` is now chosen at compile-time, based on whether the acquisition mode is streaming or rapidBlock
- Generalize and extend the Picoscope Block so that it can be used for all Picoscope variants.
- Incorporate timing messages received over the message port, when a trigger arrives
- Update to latest GR version
=> Refactor Picoscope implementation

.github/workflows/ci.yml, blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/test/CMakeLists.txt, blocklib/picoscope/test/qa_Picoscope.cc, blocklib/picoscope/test/qa_PicoscopeTiming.cc, blocklib/timing/include/TimingSource.hpp, blocklib/timing/include/timing.hpp, blocklib/timing/test/qa_timingSource.cpp
This allows the picoscope in streaming mode to match tags received from a TimingSource block and add them to the correct output port samples.
It also contains a unit-test which checks that the tags are propagated to the correct samples.
Open issues:
- Handling multiple tags within one trigger pulse width, which might not always be predictable
- Handling events where the corresponding trigger was not generated or detected (by having a timeout compared to the local clock)
- rapid block mode
- how to handle waiting for timing tags with low latency but without busy polling.
=> Picoscope: integrate timing block with picoscope block

.github/workflows/ci.yml, docker/Dockerfile
This should reduce build time and also allow to locally reuse this build environment.
For now this will not recognize changes in the gr4 Dockerfile, so the layer in this repo will not be automatically rebuilt.
This would probably need to query the upload timestamps of the gr4 and digitizer builder images and verifying that the gr4 image is older.
=> CI: create a separate docker Image based on the gr4 build image

CMakeLists.txt
Bumps the gnuradio release to match with the latest gnuradio4 and opendigitizer versions.
=> Bump GNURadio 4.0 to latest

CMakeLists.txt, blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/Picoscope4000a.hpp, blocklib/picoscope/Picoscope5000a.hpp, blocklib/picoscope/test/CMakeLists.txt, blocklib/picoscope/test/qa_Picoscope.cc, blocklib/picoscope/test/qa_PicoscopePerformanceMonitor.cc, blocklib/picoscope/test/qa_PicoscopeTiming.cc
Update Picoscope block
* Bump GR4 version and fix `qa_Picoscope` test
* Serial number are correctly assigned
* Use floats for settings
* Add picoscope performance monitoring test
* Add `gain` setting
* Add `signal_qiantity` setting
* Publish not enough space in buffer tag
* Bug fixing
When setting `sample_rate` to 20M I got the following output for each channel:
```text
Performance at 2025-02-19T09:45:13.000045, #40 dT:1.0486361 s, rate:20.3 MS/s, memory_resident:250 Mb
Performance at 2025-02-19T09:45:13.000045, #40 dT:1.048635 s, rate:20.3 MS/s, memory_resident:250 Mb
Performance at 2025-02-19T09:45:13.000045, #40 dT:1.048638 s, rate:20.3 MS/s, memory_resident:250 Mb
Performance at 2025-02-19T09:45:13.000045, #40 dT:1.048636 s, rate:20.3 MS/s, memory_resident:250 Mb
Performance at …
```
=> Update Picoscope block

CMakeLists.txt, blocklib/picoscope/CMakeLists.txt, blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/Picoscope3000a.hpp, blocklib/picoscope/Picoscope4000a.hpp, blocklib/picoscope/Picoscope5000a.hpp, blocklib/picoscope/test/CMakeLists.txt, blocklib/picoscope/test/qa_Picoscope.cc, blocklib/picoscope/test/qa_PicoscopePerformanceMonitor.cc, blocklib/picoscope/test/qa_PicoscopeTiming.cc
This PR introduces updates to the `Picoscope` block, with the main changes including:  
- Reimplementation of `RapidBlock` mode with `DataSet` support, where the output type determines the acquisition mode.  
- Option to process only completed captures in `RapidBlock` mode.  
- Support for arming/disarming input triggers.  
- Proper conversions to timebase and time interval.  
- Add support for picoscope 3000 series.
- Implement digital input and `digitalOut` port
Additional changes:  
- Removal of validation between desired and actual sample rate.  
- Refactoring: Eliminated `Settings`, `TriggerSettings`, etc., establishing a single source of truth.  
- Introduction of an internal `TagReader` for the `work()` function.  
- Fix Picoscope performance monitor.  
- General refactoring and …
=> Picoscope block updates

blocklib/picoscope/CMakeLists.txt, blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/Picoscope3000a.hpp, blocklib/picoscope/Picoscope4000a.hpp, blocklib/picoscope/Picoscope5000a.hpp, blocklib/picoscope/Picoscope6000.hpp, blocklib/picoscope/test/qa_Picoscope.cc, blocklib/timing/README.md
This PR includes the following updates:
- Bump GR4 version  
- Added support for the PicoScope 6000 series  
- Implement triggering on digital ports  
- Implemented `findDigitalTrigger` for streaming mode  
- Add test for the digital trigger (skipped by default)  
- Minor updates to the timing documentation  
- Small code improvements and fixes  
**Notes**
- The changes were tested locally with a PicoScope 5000a.  
- Digital port triggering was tested using `test-timing` for trigger configuration an generation.
- The PicoScope 6000 implementation compiles successfully but was not tested with actual hardware.
=> Picoscope updates

docker/Dockerfile
updates etherbone and saftlib to the latest releases. This will also rebuild the Docker container to be based on the latest gr4-build container, so gr-digitizers and opendigitizer will get built with emscripten 4.
=> Docker: update timing dependencies

CMakeLists.txt
gnuradio4
imgui: imgui 1.91.5 -> 1.91.9b-docking
=> CMake: Bump Dependencies

blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/test/qa_TimingMatcher.cc
TimingMatcher takes into account dropped samples in streaming mode.
Add Tag with N_DROPPED_SAMPLES for streaming mode. 
Add extended unit test to qa_TimingMatcher
Note: it was tested locally with Picoscope 5000a. But some streaming tests failed. But it turned out that for the main brach same tests failed as well. This has to be investigated further.
=> TimingMatcher takes into account dropped samples in streaming mode.

blocklib/picoscope/Picoscope.hpp, blocklib/picoscope/TimingMatcher.hpp, blocklib/picoscope/test/qa_TimingMatcher.cc
The PR contains the following changes:
Fix alignTagRelativeToLastMatched: return nullopt if _lastMatchedTag is not set
Revert "TimingMatcher takes into account dropped samples in streaming mode."
Picoscope: fix out of bounds read for picoscope data
Add diagnostics to TimeMatcher if index of last matched tag  is calculated wrongly.
=> Add matcher diagnistics and bug fixing

blocklib/timing/include/timing.hpp
Creating a CircularBuffer with trivially copyable Objects of a non-power-of-two size currently leads to a ring-buffer size that is incompatible with the way the Circular buffer calculates its internal indices. See https://github.com/fair-acc/gnuradio4/pull/622 for more details and proposed fixes.
This should also increase the cache performance for accessing the Event structure.
=> Timing: Align `Event` struct to power of two
